added compute_fk and ik client
wuisky/hello_moveit pull request #14
Opened 2024-02-15 06:54 UTC by Sunhwi-K

2024-02-20 01:02 UTC, wuisky requested changes

2024-02-20 01:02 UTC, wuisky commented on script/moveit_client.py
> +    msg1 = msg
ここの変数がmutableなので=でコピーしても意味ない。どうしてもコピーしたければdeepcopy使うが、ここはmsgそのまま使えば良い

2024-02-20 01:02 UTC, wuisky commented on script/moveit_client.py
> +    msg2 = JointState()
IK起点の初期角度代入しなければ意味ない。msg2とかの変数名もよくない

2024-02-20 01:02 UTC, wuisky commented on script/moveit_client.py
> +    current_tcp_pose = compute_fk(node, joint_state=msg)
JointState空のままでfk計算できるの？

2024-02-20 01:16 UTC, Sunhwi-K commented on script/moveit_client.py
> +    current_tcp_pose = compute_fk(node, joint_state=msg)
@wuisky 
レビューありがとうございます！
コメントアウトした箇所にも記載しましたが、JointStateは空のまま受け渡すと現在の/joint_statesを参照してFK/IK計算をしてくれるみたいです。
きちんとトピックをsubscribeするなら、subscriberを走らせながら並列でmainを実行する必要がありますが、その箇所も追記した方がよろしいでしょうか？

変数名や代入についても指摘ありがとうございます。直しておきます

2024-02-20 01:59 UTC, wuisky commented on script/moveit_client.py
> +    current_tcp_pose = compute_fk(node, joint_state=msg)
>>JointStateは空のまま受け渡すと現在の/joint_statesを参照してFK/IK計算をしてくれるみたいです。
この情報のソースはどこからわかったですか？

2024-02-20 02:14 UTC, Sunhwi-K commented on script/moveit_client.py
> +    current_tcp_pose = compute_fk(node, joint_state=msg)
たしかトピック(/joint_states)をsubscribeしてcompute_fk/ikを実行したときと、subscribeせずに(空のJointStateのまま)実行したときとで同じ結果が返ってきたのでそう思っていました。
ただおっしゃるように公式のreference読んだわけじゃないので、きちんと引数を設定した方がいいかもしれないです...

2024-02-20 03:07 UTC, wuisky commented on script/moveit_client.py
> +    current_tcp_pose = compute_fk(node, joint_state=msg)
ソースコード読みました。結論からいうと、渡さなくても現在地から取るようになってる
https://github.com/ros-planning/moveit2/blob/humble/moveit_ros/move_group/src/move_group_capability.cpp

2024-02-20 03:43 UTC, Sunhwi-K commented on script/moveit_client.py
> +    current_tcp_pose = compute_fk(node, joint_state=msg)
@wuisky 
ありがとうございます！では一旦/joint_statesのsubscriberは作らずに、引数(msg)だけ修正するようにします。

2024-02-21 01:47 UTC, Sunhwi-K commented on script/moveit_client.py
> +    current_tcp_pose = compute_fk(node, joint_state=msg)
@wuisky 
遅くなってすいません。compute_fk/ikの仕様を少し変えました（引数のjoint stateのデフォルトをNoneにして、指定されない場合は現在のjoint_statesを参照）ご確認お願いします。

2024-02-21 02:41 UTC, wuisky requested changes

2024-02-21 02:41 UTC, wuisky commented on script/moveit_client.py
> +        req.robot_state.joint_state = JointState()
引数のjoint_stateがなければからのJointState()代入すらいらないかも　試してみて。
そしたら
```python
if joint_state:
    req.robot_state.joint_state = joint_state
```
と書こう

2024-02-21 02:41 UTC, wuisky commented on script/moveit_client.py
> +        req.ik_request.robot_state.joint_state = JointState()
同じく

2024-02-21 02:59 UTC, Sunhwi-K commented on script/moveit_client.py
> +        req.ik_request.robot_state.joint_state = JointState()
@wuisky 
ご指摘通りJointState()の代入も不要でした！
if文の中身を指摘通りに修正しました

2024-02-21 03:41 UTC, wuisky approved these changes, later dismissed

2024-02-21 03:41 UTC, wuisky reviewed
チェット待って　まだマーじしないで

2024-02-21 03:44 UTC, wuisky commented
@Sunhwi-K  mypyエラー出てる　解消してみて
Incompatible default for argument "joint_state" (default has type "None", argument has type "JointState")Mypy[assignment](https://mypy.readthedocs.io/en/latest/_refs.html#code-assignment)

2024-02-21 03:47 UTC, Sunhwi-K commented
@wuisky 
承知しました。別件があるのでちょっとだけ遅くなります。

2024-02-21 03:56 UTC, wuisky requested changes

2024-02-21 03:56 UTC, wuisky commented on script/moveit_client.py
> +from std_msgs.msg import String
使ってないのにimportしないで

2024-02-21 03:56 UTC, wuisky commented on script/moveit_client.py
> +from typing import List
使っていない

2024-02-21 04:02 UTC, wuisky requested changes

2024-02-21 04:02 UTC, wuisky commented on script/moveit_client.py
> +    initial_joint_state: JointState = None) -> JointState:
`
joint_state: Optional[JointState] = None) -> Pose:
`

2024-02-21 04:02 UTC, wuisky commented on script/moveit_client.py
> +    joint_state: JointState = None) -> Pose:
`
joint_state: Optional[JointState] = None) -> Pose:
`

2024-02-21 05:10 UTC, Sunhwi-K commented on script/moveit_client.py
> +    joint_state: JointState = None) -> Pose:
@wuisky 
遅くなってすいません。importの件とmypyの件修正しました（書いてくださってありがとうございます！）

2024-02-21 05:24 UTC, wuisky requested changes

2024-02-21 05:24 UTC, wuisky commented on script/moveit_client.py
from typing import Optional 
は2行目に置きましょう。isort使ってください

2024-02-21 05:33 UTC, Sunhwi-K commented on script/moveit_client.py
@wuisky 
ありがとうございます！isort使って修正しました

2024-02-21 05:53 UTC, wuisky approved these changes
今回はこれぐらいで勘弁してやる　マージOKです

2024-02-21 06:39 UTC, merged